server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: publication-system

  datasource:
    url: jdbc:h2:mem:publication-system;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: WdC
    password: student

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

cors:
    allowed:
      origins: http://localhost:3000